main: net.novauniverse.terrasmp.TerraSMP
name: TerraSMP
description: TerraSMP Plugin
version: 1.0

softdepend: [CombatTagPlus]
depend: [NovaCore, Factions, LabyApi, VillagerGUIApi, LuckPerms]

permissions:
   terrasmp.sign.selectcontinent:
      description: Access to creating continent selector signs
      default: op
   terrasmp.nojoinmessage:
      description: Hide join message
      default: false
   terrasmp.noquitmessage:
      description: Hide quit message
      default: false
   terrasmp.customflag:
      description: Set your flag in the tablist
      default: op
   terrasmp.coloredchat:
      description: Use chat colors
      default: op
   terrasmp.joinfullserver:
       description: Allow players to join even if the server is full
       default: op
   group.vip:
      default: false

commands:
  suicide: